$testFiles = Get-ChildItem "tests/*.test.ts"
foreach ($file in $testFiles) {
    $content = Get-Content $file.FullName -Raw
    $original = $content
    
    $content = $content -replace "from '\.\./src/core/eval-engine\.js'", "from '../src/core/observability/eval-engine.js'"
    $content = $content -replace "from '\.\./src/core/hooks\.js'", "from '../src/core/core/hooks.js'"
    $content = $content -replace "from '\.\./src/core/langfuse-client\.js'", "from '../src/core/observability/langfuse-client.js'"
    $content = $content -replace "from '\./src/core/model-adapter\.js'", "from './src/core/llm/model-adapter.js'"
    $content = $content -replace "from '\.\./src/core/model-adapter\.js'", "from '../src/core/llm/model-adapter.js'"
    $content = $content -replace "from '\.\./src/core/tool-registry\.js'", "from '../src/core/tools/tool-registry.js'"
    $content = $content -replace "from '\.\./src/core/memory-log\.js'", "from '../src/core/memory/memory-log.js'"
    $content = $content -replace "from '\.\./src/core/orchestrator\.js'", "from '../src/core/engine/orchestrator.js'"
    $content = $content -replace "from '\.\./src/core/decomposer\.js'", "from '../src/core/engine/decomposer.js'"
    $content = $content -replace "from '\.\./src/core/security-scanner\.js'", "from '../src/core/security/security-scanner.js'"
    $content = $content -replace "from '\.\./src/core/skill-runtime\.js'", "from '../src/core/agents/skill-runtime.js'"
    $content = $content -replace "from '\.\./src/core/sop-registry\.js'", "from '../src/core/sop/sop-registry.js'"
    $content = $content -replace "from '\.\./src/core/sop-engine\.js'", "from '../src/core/sop/sop-engine.js'"
    $content = $content -replace "from '\.\./src/core/tracer\.js'", "from '../src/core/observability/tracer.js'"
    $content = $content -replace "from '\.\./src/core/response-cache\.js'", "from '../src/core/security/response-cache.js'"
    $content = $content -replace "from '\.\./src/core/input-guard\.js'", "from '../src/core/security/input-guard.js'"
    $content = $content -replace "from '\.\./src/core/output-guard\.js'", "from '../src/core/security/output-guard.js'"
    $content = $content -replace "from '\.\./src/core/privilege-guard\.js'", "from '../src/core/security/privilege-guard.js'"
    $content = $content -replace "from '\.\./src/core/rate-limiter\.js'", "from '../src/core/security/rate-limiter.js'"
    $content = $content -replace "from '\.\./src/core/agent-manager\.js'", "from '../src/core/agents/agent-manager.js'"
    $content = $content -replace "from '\.\./src/core/sub-agent\.js'", "from '../src/core/agents/sub-agent.js'"
    $content = $content -replace "from '\.\./src/core/failure-classifier\.js'", "from '../src/core/agents/failure-classifier.js'"
    $content = $content -replace "from '\.\./src/core/sandbox-executor\.js'", "from '../src/core/agents/sandbox-executor.js'"
    $content = $content -replace "from '\.\./src/core/docker-sandbox\.js'", "from '../src/core/agents/docker-sandbox.js'"
    $content = $content -replace "from '\.\./src/core/mcp-client\.js'", "from '../src/core/mcp/mcp-client.js'"
    $content = $content -replace "from '\.\./src/core/mcp-server\.js'", "from '../src/core/mcp/mcp-server.js'"
    $content = $content -replace "from '\.\./src/core/gnap-queue\.js'", "from '../src/core/gnap/gnap-queue.js'"
    $content = $content -replace "from '\.\./src/core/memory-store\.js'", "from '../src/core/memory/memory-store.js'"
    $content = $content -replace "from '\.\./src/core/memory-temporal\.js'", "from '../src/core/memory/memory-temporal.js'"
    $content = $content -replace "from '\.\./src/core/memory-agentic\.js'", "from '../src/core/memory/memory-agentic.js'"
    $content = $content -replace "from '\.\./src/core/state-manager\.js'", "from '../src/core/memory/state-manager.js'"
    $content = $content -replace "from '\.\./src/core/prompt-builder\.js'", "from '../src/core/llm/prompt-builder.js'"
    $content = $content -replace "from '\.\./src/core/provider-registry\.js'", "from '../src/core/llm/provider-registry.js'"
    $content = $content -replace "from '\.\./src/core/ollama-adapter\.js'", "from '../src/core/llm/ollama-adapter.js'"
    $content = $content -replace "from '\.\./src/core/cost-tracker\.js'", "from '../src/core/observability/cost-tracker.js'"
    $content = $content -replace "from '\.\./src/core/promptfoo-client\.js'", "from '../src/core/observability/promptfoo-client.js'"
    $content = $content -replace "from '\.\./src/core/pattern-selector\.js'", "from '../src/core/sop/pattern-selector.js'"
    $content = $content -replace "from '\.\./src/core/pattern-registry\.js'", "from '../src/core/sop/pattern-registry.js'"
    $content = $content -replace "from '\.\./src/core/evolution\.js'", "from '../src/core/core/evolution.js'"
    $content = $content -replace "from '\.\./src/core/types\.js'", "from '../src/core/core/types.js'"
    $content = $content -replace "from '\.\./src/core/index\.js'", "from '../src/core/core/index.js'"
    $content = $content -replace "from '\.\./src/core/engine\.js'", "from '../src/core/engine/engine.js'"
    $content = $content -replace "from '\.\./src/core/agent\.js'", "from '../src/core/engine/agent.js'"
    $content = $content -replace "from '\.\./src/core/plan-executor\.js'", "from '../src/core/engine/plan-executor.js'"
    $content = $content -replace "from '\.\./src/core/result-synthesizer\.js'", "from '../src/core/engine/result-synthes.js'"
    $content = $content -replace "from '\.\./src/core/memory\.js'", "from '../src/core/memory/memory.js'"
    $content = $content -replace "from '\.\./src/core/memory-compressor\.js'", "from '../src/core/memory/memory-compressor.js'"
    $content = $content -replace "from '\.\./src/core/code-parser\.js'", "from '../src/core/agents/code-parser.js'"
    $content = $content -replace "from '\.\./src/core/janitor\.js'", "from '../src/core/agents/janitor.js'"
    $content = $content -replace "from '\.\./src/core/skills-index-manager\.js'", "from '../src/core/agents/skills-index-manager.js'"
    $content = $content -replace "from '\.\./src/core/litellm-adapter\.js'", "from '../src/core/llm/litellm-adapter.js'"
    $content = $content -replace "from '\.\./src/core/gnap-agent-card\.js'", "from '../src/core/gnap/gnap-agent-card.js'"
    
    if ($content -ne $original) {
        Set-Content $file.FullName $content -NoNewline
        Write-Host "Updated: $($file.Name)"
    }
}
Write-Host "Done"